env = HYPRSHOT_DIR, /home/ashlyn/Pictures/Screenshots

# Screenshot a window
bind = $mainMod, S, exec, hyprshot -m window
# Screenshot a monitor
# bind = , S, exec, hyprshot -m output
# Screenshot a region
bind = $shiftMod, S, exec, hyprshot -m region
