
# Monitors
$laptop_monitor = eDP-1
$monitor_2 = HDMI-A-1

# Files
$Verdania_Temple = ~/Pictures/Backgrounds/Verdania/Verdania_Temple.png
preload = $Verdania_Temple

# wallpaper = , $Verdania_Temple
wallpaper = $laptop_monitor, $Verdania_Temple
wallpaper = $monitor_2, $Verdania_Temple
