$green-light = rgba(c6e8aeff)

# $active-border-a = rgba(33ccffee)
# $active-border-b = rgba(00ff99ee)
$active-border-a = rgba(2bff88ee)
$active-border-b = rgba(2bd2ffee)
$active-border-c = rgba(fa8bffee)

# $inactive-border = rgba(595959aa)
$inactive-border = rgba(594759aa)

$inactive-border-a = rgba(47594ebb)
$inactive-border-b = rgba(475459bb)
$inactive-border-c = rgba(594759bb)

# $decoration-shadow = rgba(1a1a1aee)
$decoration-shadow = rgba(1a1a1aee)
