env = HYPRSHOT_DIR, /home/ashlyn/Pictures/Screenshots

# Screenshot a window
bind = $mainMod, S, exec, hyprshot -m window --freeze
# Screenshot a monitor
bind = $mainMod ALT, S, exec, hyprshot -m output --freeze
# Screenshot a region
bind = $mainMod SHIFT, S, exec, hyprshot -m region --freeze
