# Monitors
$laptop_monitor = eDP-1
$monitor_2 = HDMI-A-1

# Files
$Verdania_Temple = ~/Pictures/Backgrounds/Verdania/Verdania_Temple.png
$Pendragor = ~/Pictures/Backgrounds/Verdania/Verdania_Pendragor.png
$Castle = ~/Pictures/Backgrounds/Verdania/Verdania_Castle_Lantern.png

splash = false


wallpaper {
    monitor = $laptop_monitor
    path = $Verdania_Temple
    fit_mode = cover
}

wallpaper {
    monitor = $monitor_2
    path = $Pendragor
    fit_mode = cover
}

wallpaper {
    monitor =
    fit_mode = cover # default
    path = $Castle
}
