# See https://wiki.hypr.land/Configuring/Monitors/
# monitor = ,preferred,auto,auto
# $laptop_monitor = eDP-1
# monitor = $laptop_monitor, preferred, 3328x0, 1.0
# $monitor_2 = HDMI-A-1
# monitor = $monitor_2, preferred,1280x0,1.0

$laptop_monitor = eDP-1
monitor = $laptop_monitor, preferred, 0x0, 1.0
$monitor_2 = HDMI-A-1
monitor = $monitor_2, preferred,auto-left,1.0
$tv_monitor = desc: Ines GmbH NS-55F301NA22 0x01010101
monitor = $tv_monitor, preferred, auto,1.5, mirror, $laptop_monitor
# monitor = $tv_monitor, preferred, auto-right,1.5

# $tv_monitor = HDMI-A-1
# monitor = $tv_monitor, preferred, auto, 1, mirror, $laptop_monitor

# change monitor to high resolution, the last argument is the scale factor
# monitor = , preferred, auto, 1

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

# toolkit-specific scale
env = GDK_SCALE,1
env = XCURSOR_SIZE,32
env = qt_qpa_platformtheme, qt6ct
