##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule = float = on match:class = ^(nm-connection-editor)$
windowrule = float = on match:class = ^(pavucontrol)$

# windowrule = opacity = 0.92 0.85, Dolphin
windowrule = match:class ^(dolphin)$, opacity 0.92 0.85

# windowrule = workspace = gaming match:class =

windowrule{
  name = balatro-gaming
  match:class = steam_app_2379780
  workspace = name:gaming
}

windowrule{
  name = silksong-gaming
  match:class = Hollow Knight Silksong
  workspace = name:gaming
}

windowrule{
  name = minecraft-gaming
  match:class = Minecraft.*
  workspace = name:gaming
}

windowrule{
  name = hardrock-gaming
  match:class = HardRock TerraFirmaCraft.*
  workspace = name:gaming
}

windowrule{
  name = slay-the-spire-gaming
  match:class = Slay the Spire
  workspace = name:gaming
  center = on
  fullscreen = on
}

windowrule{
  name = mod-the-spire-gaming
  match:class = Modded Slay the Spire
  workspace = name:gaming
  center = on
  fullscreen = on
}

windowrule{
  name = mts-launcher-gaming
  match:class = com-evacipated-cardcrawl-modthespire-Loader
  workspace = name:gaming
  center = on
  # fullscreen = on
}

windowrule{
  name = center-discord
  match:class = discord
  workspace = name:discord silent
  center = on
}
