##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule = float = on match:class = ^(nm-connection-editor)$
windowrule = float = on match:class = ^(pavucontrol)$

# windowrule = opacity = 0.92 0.85, Dolphin
windowrule = match:class ^(dolphin)$, opacity 0.92 0.85


# windowrule = match:class kitty, match:title nmtui, float on


# windowrule = float,class:^(nmtui)$
# windowrule = match:class nmtui, float on
